name = "pos-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = "d2c1276fa8c98af957577e3a5cf8480f"

[vars]
TIMEZONE = "Asia/Manila"

[[d1_databases]]
binding = "DB"
database_name = "pos-db"
database_id = "f088097e-c342-4ce5-a65e-721d45bc1596"
migrations_dir = "migrations"